// ==========================================================================
// FHE Traders — Product catalog data
// Used by products.html (grid), product.html (detail pages) and search.js.
//
// STRUCTURE
//   Each entry is a BRAND-LEVEL or TYPE-LEVEL product card. Individual
//   sizes / capacities / ratings live in `models` and render as selectable
//   chips on the detail page — picking one updates the WhatsApp message.
//
// FIELDS
//   id          unique slug, used in product.html?id=...
//   name        card + page title
//   category    must match a key in CATEGORY_LABELS (products.html / product.html)
//               and a data-category colour rule in css/style.css
//   icon        SVG symbol id, used as the fallback when `image` is null
//   image       path under images/products/ — null falls back to the icon tile
//   badge       "popular" | "new" | null
//   brands      optional: brand names stocked, for type-level cards (fans, lighting)
//   models      optional: selectable variants shown on the detail page
//   modelsLabel optional: heading above the model chips (default "Available Models")
//   shortDesc   one line, shown on the grid card
//   specs       bullet list on the detail page
//   description paragraph on the detail page
//
// NOTE ON MODEL LISTS: capacities reflect the range FHE Traders stocks across
// each line. Not every rating is available in every brand at all times — the
// detail pages carry a "confirm current stock" note, and the WhatsApp enquiry
// button passes the selected model through with the message.
// ==========================================================================

const PRODUCTS = [

  // ======================================================================
  // ELECTRICAL FITTINGS
  // ======================================================================
  {
    id: "mekaal-fittings",
    name: "Mekaal Electrical Fittings",
    category: "fittings",
    icon: "icon-plug",
    image: "images/products/mekaal-fittings.jpg",
    badge: "popular",
    brands: ["Mekaal"],
    modelsLabel: "Available Items",
    models: ["1-Gang Switch", "2-Gang Switch", "3-Gang Switch", "5-Gang Board", "6-Gang Board", "5A Socket", "15A Power Socket", "2-Pin Socket", "3-Pin Socket", "Fan Dimmer / Regulator", "Bell Push", "TV & Telephone Outlet", "Switch-Socket Combined Board", "Blank Plate", "Lamp Holder", "3-Pin Plug Top"],
    shortDesc: "Complete Mekaal switch, socket and board range for home and commercial wiring.",
    specs: [
      "Full range: switches, sockets, boards, regulators and accessories",
      "Standard gang sizes: 1, 2, 3, 5 and 6 gang",
      "Socket ratings: 5A and 15A, 2-pin and 3-pin",
      "Fits standard Pakistani flush and surface boxes",
      "Ideal for: New wiring, rewiring and switchboard replacement",
    ],
    description: "The complete Mekaal fittings line — switches, sockets, combined boards, fan regulators, bell pushes and plug tops — stocked in the gang sizes and ratings used in everyday Pakistani domestic and commercial wiring. Mekaal is a dependable mid-range choice for contractors who want a consistent look across a whole property without moving to premium pricing. Message us on WhatsApp with your item list and quantities for a quote.",
  },
  {
    id: "evoo-fittings",
    name: "Evoo Electrical Fittings",
    category: "fittings",
    icon: "icon-plug",
    image: "images/products/evoo-fittings.jpg",
    badge: null,
    brands: ["Evoo"],
    modelsLabel: "Available Items",
    models: ["1-Gang Switch", "2-Gang Switch", "3-Gang Switch", "5-Gang Board", "6-Gang Board", "5A Socket", "15A Power Socket", "2-Pin Socket", "3-Pin Socket", "Fan Dimmer / Regulator", "Bell Push", "TV & Telephone Outlet", "Switch-Socket Combined Board", "Blank Plate", "Lamp Holder", "3-Pin Plug Top"],
    shortDesc: "Full Evoo fittings range — switches, sockets, boards and accessories.",
    specs: [
      "Full range: switches, sockets, boards, regulators and accessories",
      "Standard gang sizes: 1, 2, 3, 5 and 6 gang",
      "Socket ratings: 5A and 15A, 2-pin and 3-pin",
      "Matching plate finishes across the range",
      "Ideal for: Complete home or office switchboard fit-outs",
    ],
    description: "Evoo's fittings range covers everything needed for a full switchboard fit-out, with matching plate finishes so switches, sockets and blanks look consistent across every room. Stocked alongside Evoo cable and lighting, which makes it a straightforward single-brand specification for a whole property.",
  },
  {
    id: "zec-fittings",
    name: "Zec Electrical Fittings",
    category: "fittings",
    icon: "icon-plug",
    image: "images/products/zec-fittings.jpg",
    badge: null,
    brands: ["Zec"],
    modelsLabel: "Available Items",
    models: ["1-Gang Switch", "2-Gang Switch", "3-Gang Switch", "5-Gang Board", "6-Gang Board", "5A Socket", "15A Power Socket", "2-Pin Socket", "3-Pin Socket", "Fan Dimmer / Regulator", "Bell Push", "TV & Telephone Outlet", "Switch-Socket Combined Board", "Blank Plate", "Lamp Holder", "3-Pin Plug Top"],
    shortDesc: "Zec switches, sockets and boards in all standard gang sizes and ratings.",
    specs: [
      "Full range: switches, sockets, boards, regulators and accessories",
      "Standard gang sizes: 1, 2, 3, 5 and 6 gang",
      "Socket ratings: 5A and 15A, 2-pin and 3-pin",
      "Fits standard flush and surface mounting boxes",
      "Ideal for: Budget-conscious wiring jobs and rental units",
    ],
    description: "Zec covers the same standard gang sizes and socket ratings as the rest of our fittings lines at a keener price point, which makes it a common pick for rental units, site accommodation and jobs where fit-out cost is the deciding factor.",
  },

  // ======================================================================
  // SOLAR PANELS
  // ======================================================================
  {
    id: "canadian-solar-panel",
    name: "Canadian Solar Panel 585W – 720W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/canadian-solar-panel.jpg",
    badge: "popular",
    brands: ["Canadian Solar"],
    modelsLabel: "Available Wattages",
    models: ["585W", "600W", "615W", "630W", "650W", "670W", "700W", "720W"],
    shortDesc: "Tier-1 Canadian Solar modules from 585W up to 720W for home and commercial arrays.",
    specs: [
      "Power output: 585W – 720W per module",
      "Cell technology: Monocrystalline PERC / N-type TOPCon",
      "Bifacial and monofacial options across the range",
      "Standard manufacturer product and performance warranty",
      "Ideal for: Residential rooftops through to commercial ground-mount",
    ],
    description: "Canadian Solar is one of the longest-established Tier-1 module manufacturers, and the 585W–720W range covers everything from a standard house rooftop to a full commercial array. The higher wattages cut the number of modules, clamps and stand rails needed for a given system size, which brings down both installation time and structure cost. Pairs with any of the hybrid inverters we stock.",
  },
  {
    id: "crown-solar-panel",
    name: "Crown Solar Panel 620W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/crown-solar-panel.jpg",
    badge: null,
    brands: ["Crown"],
    modelsLabel: "Available Wattage",
    models: ["620W"],
    shortDesc: "620W Crown module — a cost-effective high-wattage panel for standard installs.",
    specs: [
      "Power output: 620W per module",
      "Cell technology: Monocrystalline half-cut cells",
      "High-wattage format reduces module count per kW",
      "Standard manufacturer warranty",
      "Ideal for: Residential and small commercial rooftop systems",
    ],
    description: "A single high-wattage module at a competitive price point. At 620W it sits in the same size class as the premium brands, so it uses the same stands and clamps, but keeps the per-watt cost down on systems where budget is the driving constraint.",
  },
  {
    id: "longi-solar-panel",
    name: "Longi Solar Panel 600W – 650W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/longi-solar-panel.jpg",
    badge: "popular",
    brands: ["Longi"],
    modelsLabel: "Available Wattages",
    models: ["600W", "610W", "620W", "630W", "640W", "650W"],
    shortDesc: "Longi Hi-MO high-efficiency modules, 600W to 650W.",
    specs: [
      "Power output: 600W – 650W per module",
      "Cell technology: Monocrystalline (Hi-MO series, HPBC / TOPCon)",
      "Among the highest conversion efficiencies in the mainstream market",
      "Strong low-light and high-temperature performance",
      "Ideal for: Roofs where space is limited and output per m² matters",
    ],
    description: "Longi consistently sits at the top of the efficiency tables, and the Hi-MO series is the module to specify when roof area is the limiting factor rather than budget. The extra efficiency means more generation from the same footprint, which matters most on constrained urban rooftops.",
  },
  {
    id: "jinko-solar-panel",
    name: "Jinko Solar Panel 585W – 620W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/jinko-solar-panel.jpg",
    badge: null,
    brands: ["Jinko Solar"],
    modelsLabel: "Available Wattages",
    models: ["585W", "590W", "600W", "610W", "620W"],
    shortDesc: "Jinko Tiger Neo N-type modules from 585W to 620W.",
    specs: [
      "Power output: 585W – 620W per module",
      "Cell technology: N-type TOPCon (Tiger Neo series)",
      "Lower annual degradation than standard P-type modules",
      "Good performance in high ambient temperatures",
      "Ideal for: Long-life residential and commercial installations",
    ],
    description: "Jinko's Tiger Neo N-type modules degrade more slowly than conventional P-type panels, so they hold output better across a 25-year system life. The lower temperature coefficient also helps in Pakistani summer conditions, where panel temperature routinely runs well above the rating conditions.",
  },
  {
    id: "ja-solar-panel",
    name: "JA Solar Panel 600W – 650W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/ja-solar-panel.jpg",
    badge: null,
    brands: ["JA Solar"],
    modelsLabel: "Available Wattages",
    models: ["600W", "610W", "620W", "630W", "640W", "650W"],
    shortDesc: "JA Solar DeepBlue modules, 600W to 650W, for residential and commercial use.",
    specs: [
      "Power output: 600W – 650W per module",
      "Cell technology: N-type / PERC monocrystalline (DeepBlue series)",
      "Half-cut cell design for better shade tolerance",
      "Bifacial options available in the higher wattages",
      "Ideal for: Rooftop and ground-mount arrays of any size",
    ],
    description: "JA Solar's DeepBlue line is a widely-installed Tier-1 module with a strong track record in this market. The half-cut cell layout limits the output loss when part of a panel is shaded, which is useful on rooftops with water tanks, parapets or neighbouring buildings casting partial shade.",
  },
  {
    id: "tcl-solar-panel",
    name: "TCL Solar Panel 585W – 620W",
    category: "solar-panels",
    icon: "icon-panel",
    image: "images/products/tcl-solar-panel.jpg",
    badge: "new",
    brands: ["TCL"],
    modelsLabel: "Available Wattages",
    models: ["585W", "595W", "605W", "615W", "620W"],
    shortDesc: "TCL monocrystalline modules from 585W to 620W.",
    specs: [
      "Power output: 585W – 620W per module",
      "Cell technology: Monocrystalline half-cut cells",
      "Standard high-wattage module format",
      "Manufacturer product and performance warranty",
      "Ideal for: Value-focused residential and commercial systems",
    ],
    description: "TCL's module range covers the mainstream 585W–620W band at a competitive price. Physically it matches the other high-wattage panels we stock, so it can be mixed into an existing stand and clamp specification without changing the mounting structure.",
  },

  // ======================================================================
  // GALVANIZED SOLAR STANDS
  // ======================================================================
  {
    id: "l2-stand-c-type",
    name: "L2 Galvanized Solar Stand — C Type",
    category: "solar-stands",
    icon: "icon-stand",
    image: "images/products/l2-stand-c-type.jpg",
    badge: null,
    modelsLabel: "Configuration",
    models: ["L2 / C Type"],
    shortDesc: "Two-level galvanized C-channel stand for compact rooftop arrays.",
    specs: [
      "Structure: L2 (two-level) galvanized steel",
      "Section profile: C-channel",
      "Hot-dip galvanized finish for rust resistance",
      "Supplied with fixing hardware and module clamps",
      "Ideal for: Small to mid-size rooftop arrays",
    ],
    description: "A two-level C-channel stand for rooftop arrays where height and wind loading are moderate. The C-section is the lighter and more economical of the two profiles, and the hot-dip galvanized finish stands up to monsoon and coastal conditions far better than a painted mild-steel frame.",
  },
  {
    id: "l2-stand-u-type",
    name: "L2 Galvanized Solar Stand — U Type",
    category: "solar-stands",
    icon: "icon-stand",
    image: "images/products/l2-stand-u-type.jpg",
    badge: null,
    modelsLabel: "Configuration",
    models: ["L2 / U Type"],
    shortDesc: "Two-level galvanized U-channel stand with a heavier section profile.",
    specs: [
      "Structure: L2 (two-level) galvanized steel",
      "Section profile: U-channel",
      "Heavier profile than C type for higher wind loading",
      "Hot-dip galvanized finish",
      "Ideal for: Exposed rooftops and windier sites",
    ],
    description: "The same two-level layout as the C type but built on a heavier U-channel section, which gives more rigidity on exposed rooftops and open sites where wind loading is the design driver.",
  },
  {
    id: "l3-stand-c-type",
    name: "L3 Galvanized Solar Stand — C Type",
    category: "solar-stands",
    icon: "icon-stand",
    image: "images/products/l3-stand-c-type.jpg",
    badge: "popular",
    modelsLabel: "Configuration",
    models: ["L3 / C Type"],
    shortDesc: "Three-level galvanized C-channel stand for larger rooftop arrays.",
    specs: [
      "Structure: L3 (three-level) galvanized steel",
      "Section profile: C-channel",
      "Extra height clears parapets, tanks and roof obstructions",
      "Hot-dip galvanized finish",
      "Ideal for: Larger residential and small commercial arrays",
    ],
    description: "The three-level version adds height, which is what most rooftops actually need — it lifts the array clear of parapet walls, water tanks and stairwell rooms that would otherwise shade the lower row for part of the day. The most commonly specified stand in our range.",
  },
  {
    id: "l3-stand-u-type",
    name: "L3 Galvanized Solar Stand — U Type",
    category: "solar-stands",
    icon: "icon-stand",
    image: "images/products/l3-stand-u-type.jpg",
    badge: null,
    modelsLabel: "Configuration",
    models: ["L3 / U Type"],
    shortDesc: "Three-level galvanized U-channel stand for heavier-duty installs.",
    specs: [
      "Structure: L3 (three-level) galvanized steel",
      "Section profile: U-channel",
      "Heavier section for larger arrays and exposed sites",
      "Hot-dip galvanized finish",
      "Ideal for: Commercial arrays and high-wind locations",
    ],
    description: "Three-level height combined with the heavier U-channel section. Specified where the array is both tall and large enough that the extra structural margin is worth the additional steel cost.",
  },
  {
    id: "l4-stand-c-type",
    name: "L4 Galvanized Solar Stand — C Type",
    category: "solar-stands",
    icon: "icon-stand",
    image: "images/products/l4-stand-c-type.jpg",
    badge: null,
    modelsLabel: "Configuration",
    models: ["L4 / C Type"],
    shortDesc: "Four-level galvanized C-channel stand — maximum clearance height.",
    specs: [
      "Structure: L4 (four-level) galvanized steel",
      "Section profile: C-channel",
      "Maximum clearance for heavily obstructed rooftops",
      "Hot-dip galvanized finish",
      "Ideal for: Rooftops with tall obstructions or shaded lower levels",
    ],
    description: "The tallest stand in the range, for rooftops where surrounding walls, adjacent buildings or roof-mounted plant would shade a lower array. The extra clearance also leaves usable space underneath, which is often put to work as storage or a shaded roof terrace.",
  },

  // ======================================================================
  // INVERTERS
  // ======================================================================
  {
    id: "inverex-inverter",
    name: "Inverex Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/inverex-inverter.jpg",
    badge: "popular",
    brands: ["Inverex"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Pakistan's most widely installed hybrid inverter line, 1.6kW to 12kW.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: On-grid, off-grid and battery-backed hybrid",
      "Built-in MPPT solar charge controller",
      "Lithium battery communication (BMS) support on hybrid models",
      "Local warranty and after-sales service network",
    ],
    description: "Inverex is the most widely installed inverter brand in Pakistan, and that matters more than a spec sheet when something goes wrong three years in — parts and service are genuinely available. The range runs from small 1.6kW units for a few fans and lights up to 12kW for a large house or small commercial load.",
  },
  {
    id: "crown-micro-inverter",
    name: "Crown Micro Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/crown-micro-inverter.jpg",
    badge: null,
    brands: ["Crown Micro"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Crown Micro hybrid and off-grid inverters across the full 1.6kW–12kW range.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid and off-grid",
      "Built-in MPPT solar charge controller",
      "LCD display with load, solar and battery monitoring",
      "Compatible with lead-acid and lithium battery banks",
    ],
    description: "Crown Micro covers the same capacity band as the market leaders with a well-established local presence. A practical choice for standard residential systems, and it pairs naturally with Crown Micro batteries if you want a single-brand setup with matched BMS communication.",
  },
  {
    id: "itel-energy-inverter",
    name: "Itel Energy Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/itel-energy-inverter.jpg",
    badge: "new",
    brands: ["Itel Energy"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Itel Energy hybrid inverters with app monitoring, 1.6kW to 12kW.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid with grid and generator input",
      "Built-in MPPT solar charge controller",
      "WiFi / app monitoring on supported models",
      "Backed by Itel's expanding Pakistan service network",
    ],
    description: "Itel moved into solar on the back of a large existing consumer electronics and service footprint in Pakistan, which gives the brand a wider repair network than most newer entrants. The hybrid models include app monitoring so you can check generation and battery state without going up to the inverter.",
  },
  {
    id: "maxpower-inverter",
    name: "Maxpower Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/maxpower-inverter.jpg",
    badge: null,
    brands: ["Maxpower"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Maxpower hybrid and off-grid inverters from 1.6kW through 12kW.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid and off-grid",
      "Built-in MPPT solar charge controller",
      "Pure sine wave output",
      "Compatible with the Maxpower lithium battery range",
    ],
    description: "Maxpower has been in the Pakistani UPS and inverter market long enough to have a settled service network, and the solar hybrid range carries that over. Pure sine wave output across the line means no issues running motors, compressors or sensitive electronics off backup.",
  },
  {
    id: "crown-lifaan-inverter",
    name: "Crown Lifaan Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/crown-lifaan-inverter.jpg",
    badge: null,
    brands: ["Crown Lifaan"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Crown Lifaan hybrid inverters covering the full domestic capacity range.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid and off-grid",
      "Built-in MPPT solar charge controller",
      "LCD status display",
      "Ideal for: Domestic backup and daytime solar offset",
    ],
    description: "Crown Lifaan sits at the value end of the Crown line-up while covering the same capacity range. A sensible pick where the priority is getting a working hybrid system in at the lowest sensible cost rather than maximising features.",
  },
  {
    id: "longlife-inverter",
    name: "Longlife Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/longlife-inverter.jpg",
    badge: null,
    brands: ["Longlife"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Longlife hybrid inverters, 1.6kW to 12kW, for home and small commercial use.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid and off-grid",
      "Built-in MPPT solar charge controller",
      "Lead-acid and lithium battery support",
      "Ideal for: Homes and small commercial premises",
    ],
    description: "Longlife covers the full domestic and light-commercial capacity band with hybrid units that will run from solar, battery or grid as availability changes. Matched Longlife lithium batteries are stocked alongside if you want the inverter and storage from one brand.",
  },
  {
    id: "solax-inverter",
    name: "Solax Power Hybrid Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/solax-inverter.jpg",
    badge: "popular",
    brands: ["Solax Power"],
    modelsLabel: "Available Capacities",
    models: ["3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Solax X1/X3 hybrid inverters — international-grade hybrid with cloud monitoring.",
    specs: [
      "Capacity range: 3kW – 12kW",
      "Single-phase (X1) and three-phase (X3) models",
      "Dual MPPT trackers on most models",
      "SolaxCloud app and web portal monitoring",
      "International certifications, 5–10 year warranty options",
    ],
    description: "Solax is a properly international hybrid brand with cloud monitoring, dual MPPT tracking and single or three-phase options. Worth the premium over local brands where the system is large, the load is three-phase, or the owner wants proper long-term generation data rather than an LCD panel reading.",
  },
  {
    id: "nexgen-inverter",
    name: "Nexgen Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/nexgen-inverter.jpg",
    badge: null,
    brands: ["Nexgen"],
    modelsLabel: "Available Capacities",
    models: ["1.6kW", "2kW", "3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Nexgen hybrid inverters across the full 1.6kW–12kW capacity range.",
    specs: [
      "Capacity range: 1.6kW – 12kW",
      "Operating modes: Hybrid, on-grid and off-grid",
      "Built-in MPPT solar charge controller",
      "Pure sine wave output",
      "Ideal for: Residential and light commercial installations",
    ],
    description: "Nexgen covers the full domestic capacity band with hybrid units suited to standard household and small commercial loads. Widely available in this market with straightforward parts supply.",
  },
  {
    id: "solis-inverter",
    name: "Solis Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/solis-inverter.jpg",
    badge: null,
    brands: ["Solis"],
    modelsLabel: "Available Capacities",
    models: ["3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "Solis grid-tied and hybrid inverters — one of the largest global inverter makers.",
    specs: [
      "Capacity range: 3kW – 12kW",
      "Grid-tied and hybrid models",
      "Single-phase and three-phase options",
      "SolisCloud monitoring portal and app",
      "High conversion efficiency across the load range",
    ],
    description: "Solis (Ginlong) is among the largest inverter manufacturers in the world by shipment volume, with a deep grid-tied range and a growing hybrid line. A strong choice for net-metered systems where the priority is efficient export rather than battery backup.",
  },
  {
    id: "goodwe-inverter",
    name: "GoodWe Hybrid Solar Inverter",
    category: "inverters",
    icon: "icon-zap",
    image: "images/products/goodwe-inverter.jpg",
    badge: null,
    brands: ["GoodWe"],
    modelsLabel: "Available Capacities",
    models: ["3kW", "3.6kW", "4kW", "4.2kW", "5kW", "5.8kW", "6kW", "6.5kW", "6.6kW", "8kW", "10kW", "11kW", "12kW"],
    shortDesc: "GoodWe ES/ET series hybrid inverters with high-current battery charging.",
    specs: [
      "Capacity range: 3kW – 12kW",
      "Single-phase (ES/EH) and three-phase (ET) hybrid series",
      "Dual MPPT trackers, high battery charge/discharge current",
      "SEMS Portal monitoring app",
      "Compatible with the GoodWe Lynx lithium battery range",
    ],
    description: "GoodWe's hybrid range is built around fast battery charging, which is genuinely useful here — it means a system can push a lot of energy into storage during the short window when solar output is at its peak. Pairs directly with GoodWe Lynx batteries for full BMS communication and a single warranty point.",
  },

  // ======================================================================
  // LITHIUM-ION BATTERIES
  // ======================================================================
  {
    id: "huawei-battery",
    name: "Huawei LUNA Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/huawei-battery.jpg",
    badge: "popular",
    brands: ["Huawei"],
    modelsLabel: "Available Capacities",
    models: ["5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Huawei LUNA modular lithium storage — premium build with per-module optimisation.",
    specs: [
      "Capacity range: 5kWh – 32kWh (stackable modules)",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Module-level energy optimisation and monitoring",
      "Integrated pack-level fire safety design",
      "Long cycle life with 10-year warranty options",
    ],
    description: "Huawei's LUNA packs sit at the premium end of the lithium storage market. Each module is individually optimised and monitored rather than being managed only at pack level, which means one weaker module does not drag down the capacity of the whole bank — a real advantage as the system ages. Stacks in modules, so the bank can be expanded later without replacing what is already installed.",
  },
  {
    id: "australian-battery",
    name: "Australian Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/australian-battery.jpg",
    badge: null,
    brands: ["Australian"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Australian-brand LiFePO4 storage from 2.5kWh up to 32kWh banks.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with over-charge and over-discharge protection",
      "Wall-mount and rack-mount formats",
      "Ideal for: Home backup and daily solar cycling",
    ],
    description: "A full-range LiFePO4 line covering everything from a small 2.5kWh unit for essential loads through to a 32kWh bank for whole-house backup. The integrated BMS handles cell balancing and protection, and communicates with most of the hybrid inverters we stock.",
  },
  {
    id: "inverex-battery",
    name: "Inverex Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/inverex-battery.jpg",
    badge: "popular",
    brands: ["Inverex"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Inverex LiFePO4 batteries with native communication to Inverex inverters.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Native BMS communication with Inverex hybrid inverters",
      "Wall-mount and floor-stack formats",
      "Local warranty and service network",
    ],
    description: "The natural storage pairing for an Inverex inverter — the BMS talks to the inverter directly, so charge and discharge limits, state of charge and cell temperature are all handled properly rather than estimated from voltage. That matters for battery lifespan, and it also means one supplier for warranty on both halves of the system.",
  },
  {
    id: "goodwe-battery",
    name: "GoodWe Lynx Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/goodwe-battery.jpg",
    badge: null,
    brands: ["GoodWe"],
    modelsLabel: "Available Capacities",
    models: ["5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "GoodWe Lynx modular LiFePO4 storage, matched to GoodWe hybrid inverters.",
    specs: [
      "Capacity range: 5kWh – 32kWh (stackable modules)",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Plug-and-play stacking, expandable after installation",
      "Full BMS communication with GoodWe ES/ET inverters",
      "Monitored through the SEMS Portal app",
    ],
    description: "GoodWe's Lynx range stacks in modules and is designed to be added to later, so a household can start with what it can afford and expand the bank as budget allows. Paired with a GoodWe inverter the whole system reports through one app and sits under one warranty.",
  },
  {
    id: "crown-micro-battery",
    name: "Crown Micro Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/crown-micro-battery.jpg",
    badge: null,
    brands: ["Crown Micro"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Crown Micro LiFePO4 storage across the full 2.5kWh–32kWh range.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with cell balancing",
      "Wall-mount format with status display",
      "Pairs with the Crown Micro inverter range",
    ],
    description: "Crown Micro storage covers the full domestic capacity band and pairs directly with Crown Micro inverters. A practical single-brand option for a standard home system where you want inverter and battery under one supplier.",
  },
  {
    id: "crown-electra-boost-battery",
    name: "Crown Electra Boost Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/crown-electra-boost-battery.jpg",
    badge: null,
    brands: ["Crown Electra Boost"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Crown Electra Boost LiFePO4 batteries for home and commercial backup.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with protection and balancing",
      "Parallel stacking for larger banks",
      "Ideal for: Home backup and daily cycling",
    ],
    description: "The Electra Boost line covers the same capacity range with parallel stacking for larger banks. Suited to households that cycle the battery daily rather than holding it purely as outage backup.",
  },
  {
    id: "itel-battery",
    name: "Itel Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/itel-battery.jpg",
    badge: "new",
    brands: ["Itel"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Itel LiFePO4 storage backed by Itel's Pakistan service network.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with inverter communication",
      "Wall-mount format",
      "Backed by Itel's nationwide service presence",
    ],
    description: "Itel's storage range benefits from the same wide service footprint as the rest of the brand's electronics business, which is a genuine consideration on a product expected to last ten years. Pairs with Itel Energy inverters for matched BMS communication.",
  },
  {
    id: "solax-battery",
    name: "Solax Triple Power Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/solax-battery.jpg",
    badge: null,
    brands: ["Solax Power"],
    modelsLabel: "Available Capacities",
    models: ["5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Solax Triple Power modular LiFePO4 batteries with cloud monitoring.",
    specs: [
      "Capacity range: 5kWh – 32kWh (stackable modules)",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Modular stacking, expandable after installation",
      "Full communication with Solax X1/X3 hybrid inverters",
      "Monitored via SolaxCloud",
    ],
    description: "Solax Triple Power modules stack to build the bank size you need and report through SolaxCloud alongside the inverter, so generation, consumption and storage all appear in one place. The matched pairing for a Solax hybrid system.",
  },
  {
    id: "longlife-battery",
    name: "Longlife Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/longlife-battery.jpg",
    badge: null,
    brands: ["Longlife"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Longlife LiFePO4 batteries from 2.5kWh through to 32kWh banks.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with over-current and thermal protection",
      "Parallel connection for larger banks",
      "Pairs with the Longlife inverter range",
    ],
    description: "Full-range LiFePO4 storage that pairs with the Longlife inverter line for a single-brand system. Covers everything from a small essentials-only bank to whole-house backup.",
  },
  {
    id: "maxpower-battery",
    name: "Maxpower Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/maxpower-battery.jpg",
    badge: null,
    brands: ["Maxpower"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Maxpower LiFePO4 storage for home backup and daily solar cycling.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with cell balancing",
      "Wall-mount and rack formats",
      "Pairs with the Maxpower inverter range",
    ],
    description: "Maxpower storage across the full domestic capacity band, matched to the Maxpower inverter line. A settled brand in this market with straightforward local warranty support.",
  },
  {
    id: "coretech-battery",
    name: "Coretech Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/coretech-battery.jpg",
    badge: null,
    brands: ["Coretech"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Coretech LiFePO4 batteries across the full 2.5kWh–32kWh range.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with protection and balancing",
      "Wall-mount format with state-of-charge display",
      "Ideal for: Residential backup and solar storage",
    ],
    description: "Coretech covers the standard domestic capacity range with LiFePO4 packs suited to daily solar cycling as well as outage backup. Communicates with most of the hybrid inverters we stock.",
  },
  {
    id: "sunwoda-battery",
    name: "Sunwoda Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/sunwoda-battery.jpg",
    badge: null,
    brands: ["Sunwoda"],
    modelsLabel: "Available Capacities",
    models: ["5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Sunwoda LiFePO4 storage from a major global cell manufacturer.",
    specs: [
      "Capacity range: 5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Cells manufactured in-house by Sunwoda",
      "Integrated BMS with inverter communication",
      "Long cycle life rating",
    ],
    description: "Sunwoda is a large-scale cell manufacturer supplying the consumer electronics and EV industries, which means the cells inside these packs come from the same production lines rather than being bought in. That tends to show in consistency across a bank.",
  },
  {
    id: "dyness-battery",
    name: "Dyness Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/dyness-battery.jpg",
    badge: "popular",
    brands: ["Dyness"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Dyness modular LiFePO4 batteries — wide inverter compatibility.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh (stackable)",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Broad compatibility list across major inverter brands",
      "Wall-mount and rack-mount formats",
      "Parallel stacking for larger banks",
    ],
    description: "Dyness has one of the widest inverter compatibility lists in the market, which makes it the safe pick when the inverter brand is already fixed or may change later. The modular design lets the bank grow over time.",
  },
  {
    id: "pylontech-battery",
    name: "Pylontech Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/pylontech-battery.jpg",
    badge: null,
    brands: ["Pylontech"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Pylontech US-series rack batteries — the long-standing industry reference.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh (stackable modules)",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "US2000 / US3000 / US5000 rack-mount series",
      "Supported by virtually every major hybrid inverter",
      "Proven long-term field record",
    ],
    description: "Pylontech's US series is effectively the reference battery that inverter manufacturers test against, so compatibility is close to universal and the field record goes back further than most competitors. Rack-mount modules stack cleanly and can be added to year by year.",
  },
  {
    id: "jeekong-battery",
    name: "Jee Kong Lithium Battery",
    category: "batteries",
    icon: "icon-battery",
    image: "images/products/jeekong-battery.jpg",
    badge: null,
    brands: ["Jee Kong"],
    modelsLabel: "Available Capacities",
    models: ["2.5kWh", "5kWh", "10kWh", "16kWh", "32kWh"],
    shortDesc: "Jee Kong LiFePO4 storage across the full domestic capacity range.",
    specs: [
      "Capacity range: 2.5kWh – 32kWh",
      "Chemistry: LiFePO4 (lithium iron phosphate)",
      "Integrated BMS with protection and balancing",
      "Wall-mount and rack formats",
      "Ideal for: Home backup and solar self-consumption",
    ],
    description: "Jee Kong covers the standard domestic capacity band at a competitive price point, with an integrated BMS and the usual protection features. A value option where bank size matters more than brand name.",
  },

  // ======================================================================
  // VARIABLE FREQUENCY DRIVES (VFD)
  // ======================================================================
  {
    id: "invt-vfd",
    name: "INVT Variable Frequency Drive",
    category: "vfd",
    icon: "icon-gauge",
    image: "images/products/invt-vfd.jpg",
    badge: "popular",
    brands: ["INVT"],
    modelsLabel: "Available Power Ranges",
    models: ["5–7kW", "7–11kW", "11–15kW", "15–18kW", "18–22kW", "22–25kW", "25–30kW"],
    shortDesc: "INVT VFDs for solar and mains-driven pumps and motors, 5kW to 30kW.",
    specs: [
      "Power range: 5kW – 30kW",
      "Solar (DC) and mains (AC) input models",
      "Built-in MPPT on solar pump drive models",
      "Motor protection: over-current, over-voltage, dry-run and phase loss",
      "Ideal for: Agricultural pumps, tube wells and industrial motors",
    ],
    description: "INVT is one of the better-known drive manufacturers in this market, and the solar pump models are the practical answer for tube wells that would otherwise run on diesel. The built-in MPPT means the drive takes power straight from the array and varies motor speed with available sunlight, so the pump keeps running through cloud cover rather than tripping out.",
  },
  {
    id: "crown-vfd",
    name: "Crown Variable Frequency Drive",
    category: "vfd",
    icon: "icon-gauge",
    image: "images/products/crown-vfd.jpg",
    badge: null,
    brands: ["Crown"],
    modelsLabel: "Available Power Ranges",
    models: ["5–7kW", "7–11kW", "11–15kW", "15–18kW", "18–22kW", "22–25kW", "25–30kW"],
    shortDesc: "Crown VFDs covering 5kW through 30kW for pump and motor control.",
    specs: [
      "Power range: 5kW – 30kW",
      "Solar and mains input options",
      "Variable speed motor control with soft start",
      "Built-in motor protection functions",
      "Ideal for: Water pumps, fans and industrial drives",
    ],
    description: "Crown's drive range covers the full 5–30kW band used by most agricultural and light industrial pumps. Soft start alone extends motor life noticeably compared with direct-on-line starting, and the variable speed control cuts energy use on part-load duties.",
  },
  {
    id: "skypower-vfd",
    name: "Skypower Variable Frequency Drive",
    category: "vfd",
    icon: "icon-gauge",
    image: "images/products/skypower-vfd.jpg",
    badge: null,
    brands: ["Skypower"],
    modelsLabel: "Available Power Ranges",
    models: ["5–7kW", "7–11kW", "11–15kW", "15–18kW", "18–22kW", "22–25kW", "25–30kW"],
    shortDesc: "Skypower solar pump drives and VFDs from 5kW to 30kW.",
    specs: [
      "Power range: 5kW – 30kW",
      "Solar pump drive and standard VFD models",
      "MPPT tracking on solar models",
      "Dry-run and over-load protection",
      "Ideal for: Solar tube wells and irrigation pumping",
    ],
    description: "Skypower's drives are aimed squarely at solar pumping, with MPPT tracking and dry-run protection built in. Suited to irrigation installations where the drive needs to manage a wide range of available power through the day without operator attention.",
  },
  {
    id: "inverex-vfd",
    name: "Inverex Variable Frequency Drive",
    category: "vfd",
    icon: "icon-gauge",
    image: "images/products/inverex-vfd.jpg",
    badge: null,
    brands: ["Inverex"],
    modelsLabel: "Available Power Ranges",
    models: ["5–7kW", "7–11kW", "11–15kW", "15–18kW", "18–22kW", "22–25kW", "25–30kW"],
    shortDesc: "Inverex solar pump inverters and VFDs, 5kW through 30kW.",
    specs: [
      "Power range: 5kW – 30kW",
      "Solar pump inverter and standard VFD models",
      "Built-in MPPT solar tracking",
      "Motor and pump protection functions",
      "Backed by Inverex's local service network",
    ],
    description: "Inverex's drive range carries the same local service advantage as its inverters — parts and support are genuinely available across the country, which matters on a pump that a farm depends on daily. Solar models run the pump directly from the array with no battery required.",
  },
  {
    id: "fd-power-vfd",
    name: "FD Power Variable Frequency Drive",
    category: "vfd",
    icon: "icon-gauge",
    image: "images/products/fd-power-vfd.jpg",
    badge: null,
    brands: ["FD Power"],
    modelsLabel: "Available Power Ranges",
    models: ["5–7kW", "7–11kW", "11–15kW", "15–18kW", "18–22kW", "22–25kW", "25–30kW"],
    shortDesc: "FD Power VFDs for solar pumping and industrial motor control.",
    specs: [
      "Power range: 5kW – 30kW",
      "Solar and mains input models",
      "Variable speed control with soft start",
      "Over-current, over-voltage and dry-run protection",
      "Ideal for: Tube wells, irrigation and industrial motors",
    ],
    description: "FD Power covers the full 5–30kW range for both solar pumping and conventional industrial motor control. A value option where the drive specification is straightforward and cost is the deciding factor.",
  },

  // ======================================================================
  // FANS
  // ======================================================================
  {
    id: "ceiling-fan-ac-220v",
    name: "AC 220V Ceiling Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/ceiling-fan-ac-220v.jpg",
    badge: "popular",
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Blade Configurations",
    models: ["2 Blade", "3 Blade", "4 Blade", "5 Blade"],
    shortDesc: "Standard mains ceiling fans from Noor, Al Falah and Al Marth in 2 to 5 blade designs.",
    specs: [
      "Supply: AC 220V mains",
      "Blade options: 2, 3, 4 and 5 blade",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Copper winding motors",
      "Ideal for: Standard rooms on mains supply",
    ],
    description: "The conventional mains ceiling fan, stocked across Noor Fan, Al Falah and Al Marth in blade counts from two up to five. More blades generally means quieter, gentler air movement; fewer blades moves more air for the same motor. All models here use copper winding, which runs cooler and lasts longer than aluminium alternatives.",
  },
  {
    id: "ceiling-fan-ac-dc",
    name: "AC/DC Ceiling Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/ceiling-fan-ac-dc.jpg",
    badge: null,
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Blade Configurations",
    models: ["2 Blade", "3 Blade", "4 Blade", "5 Blade"],
    shortDesc: "Dual-supply fans that switch between mains and battery power automatically.",
    specs: [
      "Supply: AC 220V mains and 12V/24V DC battery",
      "Automatic changeover between mains and battery",
      "Blade options: 2, 3, 4 and 5 blade",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Ideal for: Areas with frequent load shedding",
    ],
    description: "An AC/DC fan runs from mains normally and switches itself over to a battery when the supply drops, so the room keeps moving air through load shedding without needing a UPS or inverter in the circuit. The simplest and cheapest way to keep fans running through an outage.",
  },
  {
    id: "ceiling-fan-dc-inverter-30w",
    name: "DC Inverter Ceiling Fans (30W)",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/ceiling-fan-dc-inverter-30w.jpg",
    badge: "new",
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Blade Configurations",
    models: ["2 Blade", "3 Blade", "4 Blade", "5 Blade"],
    shortDesc: "30W DC inverter fans — roughly a third of the power draw of a standard fan.",
    specs: [
      "Power consumption: approximately 30W",
      "Motor type: BLDC (brushless DC inverter)",
      "Remote control with speed steps on most models",
      "Blade options: 2, 3, 4 and 5 blade",
      "Ideal for: Homes running fans on solar or battery backup",
    ],
    description: "A BLDC inverter fan draws around 30W against roughly 80–100W for a conventional fan of the same size, which changes the arithmetic completely on a battery-backed system — the same battery bank runs three times as many fans for the same runtime. If a house is on solar, this is usually the single highest-value fan upgrade available.",
  },
  {
    id: "exhaust-fan-plastic",
    name: "Plastic Exhaust Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/exhaust-fan-plastic.jpg",
    badge: null,
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Sizes",
    models: ["6 inch", "8 inch", "10 inch", "12 inch", "18 inch", "24 inch"],
    shortDesc: "Lightweight plastic-body exhaust fans from 6 inch up to 24 inch.",
    specs: [
      "Sizes: 6, 8, 10, 12, 18 and 24 inch",
      "Body: moulded plastic — rust-proof and lightweight",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Wall and window mounting",
      "Ideal for: Kitchens, bathrooms and damp areas",
    ],
    description: "Plastic-body exhaust fans will not rust, which makes them the right choice for bathrooms, kitchens and anywhere else humidity is constant. The lighter body also makes them simpler to mount in a window or a thin partition wall. Sizes run from a small 6 inch bathroom unit up to a 24 inch for larger kitchens.",
  },
  {
    id: "exhaust-fan-metal",
    name: "Metal Exhaust Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/exhaust-fan-metal.jpg",
    badge: null,
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Sizes",
    models: ["6 inch", "8 inch", "10 inch", "12 inch", "18 inch", "24 inch"],
    shortDesc: "Heavy-duty metal-body exhaust fans, 6 inch through 24 inch.",
    specs: [
      "Sizes: 6, 8, 10, 12, 18 and 24 inch",
      "Body: pressed metal for higher-duty use",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Higher airflow than equivalent plastic models",
      "Ideal for: Commercial kitchens, workshops and factories",
    ],
    description: "Metal-body exhaust fans handle continuous duty and higher air volumes better than plastic, which is why they end up in commercial kitchens, workshops and production areas. Heavier to mount, but the right specification where the fan runs for most of the working day.",
  },
  {
    id: "bracket-fan",
    name: "Bracket Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/bracket-fan.jpg",
    badge: null,
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Sizes",
    models: ["18 inch", "24 inch"],
    shortDesc: "Wall-mounted bracket fans in 18 inch and 24 inch sizes.",
    specs: [
      "Sizes: 18 and 24 inch",
      "Wall-mounted bracket with oscillation",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Frees up floor space",
      "Ideal for: Shops, workshops, halls and verandas",
    ],
    description: "Wall-mounted fans that keep the floor clear, which is why they are the standard fit in shops, workshops and function halls. The 24 inch throws air across a much larger area than a ceiling fan and is the usual pick for open commercial spaces.",
  },
  {
    id: "pedestal-fan",
    name: "Pedestal Fans",
    category: "fans",
    icon: "icon-fan",
    image: "images/products/pedestal-fan.jpg",
    badge: null,
    brands: ["Noor Fan", "Al Falah", "Al Marth"],
    modelsLabel: "Available Sizes & Blades",
    models: ["20 inch", "24 inch", "3 Blade", "4 Blade", "6 Blade"],
    shortDesc: "Height-adjustable pedestal fans in 20 inch and 24 inch, 3 to 6 blade.",
    specs: [
      "Sizes: 20 and 24 inch",
      "Blade options: 3, 4 and 6 blade",
      "Height-adjustable stand with oscillation",
      "Brands stocked: Noor Fan, Al Falah, Al Marth",
      "Ideal for: Rooms, shops and outdoor seating areas",
    ],
    description: "Portable, height-adjustable and easily moved to wherever the air is needed. The 6 blade models move noticeably more air at lower speed settings, which makes them quieter for a given amount of cooling — worth the difference in a bedroom or at a shop counter.",
  },

  // ======================================================================
  // WIRING & CABLES
  // ======================================================================
  {
    id: "fhe-cables",
    name: "FHE Copper Cables",
    category: "wiring",
    icon: "icon-cable",
    image: "images/products/fhe-cables.jpg",
    badge: "popular",
    brands: ["FHE"],
    modelsLabel: "Available Sizes",
    models: ["3/.029", "7/.029", "7/.036", "7/.044", "7/.052", "7/.064", "7/.076", "19/.064", "19/.075", "1.0 mm²", "1.5 mm²", "2.5 mm²", "4 mm²", "6 mm²", "10 mm²", "16 mm²"],
    shortDesc: "Our own full range of pure copper single and multi-core wiring cable.",
    specs: [
      "Conductor: pure electrolytic copper",
      "Standard sizes from 3/.029 up to 19/.075",
      "Metric equivalents 1.0 mm² through 16 mm²",
      "PVC insulation rated for domestic and commercial wiring",
      "Available in single-core and multi-core / flexible",
    ],
    description: "Our own cable line, stocked in every standard size used in Pakistani domestic and commercial wiring — from 3/.029 for lighting circuits through to 19/.075 for main runs and heavy sub-circuits. Pure electrolytic copper conductor throughout: undersized or aluminium-blended cable is the single most common cause of overheating in rewiring jobs, and it is not worth the saving. Sold by coil or by the metre.",
  },
  {
    id: "evoo-cables",
    name: "Evoo Copper Cables",
    category: "wiring",
    icon: "icon-cable",
    image: "images/products/evoo-cables.jpg",
    badge: null,
    brands: ["Evoo"],
    modelsLabel: "Available Sizes",
    models: ["3/.029", "7/.029", "7/.036", "7/.044", "7/.052", "7/.064", "7/.076", "19/.064", "19/.075", "1.0 mm²", "1.5 mm²", "2.5 mm²", "4 mm²", "6 mm²", "10 mm²", "16 mm²"],
    shortDesc: "Full Evoo cable range in all standard single and multi-core sizes.",
    specs: [
      "Conductor: pure electrolytic copper",
      "Standard sizes from 3/.029 up to 19/.075",
      "Metric equivalents 1.0 mm² through 16 mm²",
      "PVC insulation, colour-coded by phase",
      "Single-core and multi-core / flexible options",
    ],
    description: "The complete Evoo cable range across all standard sizes, colour-coded by phase so a board stays readable for whoever works on it next. Stocked alongside Evoo fittings and lighting for jobs specified to a single brand throughout.",
  },

  // ======================================================================
  // LIGHTING
  // ======================================================================
  {
    id: "led-bulbs",
    name: "LED Bulbs",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/led-bulbs.jpg",
    badge: "popular",
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["5W", "7W", "9W", "12W", "15W", "18W", "24W", "30W", "40W", "50W"],
    shortDesc: "Evoo and FHE LED bulbs from 5W to 50W in warm and daylight tones.",
    specs: [
      "Wattages: 5W – 50W",
      "Colour temperatures: warm white (3000K) and daylight (6500K)",
      "Standard B22 bayonet and E27 screw bases",
      "Roughly 85% less power than an equivalent incandescent bulb",
      "Brands stocked: Evoo, FHE",
    ],
    description: "Standard LED bulbs across the full wattage range in both warm white and daylight. Available in B22 bayonet and E27 screw fittings so they drop into existing holders with no rewiring. The low draw makes them the obvious first change on any house running lights off a battery or inverter.",
  },
  {
    id: "smd-lights",
    name: "SMD Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/smd-lights.jpg",
    badge: null,
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["3W", "5W", "7W", "9W", "12W", "15W", "18W", "24W"],
    shortDesc: "Recessed and surface SMD downlights, 3W to 24W, round and square.",
    specs: [
      "Wattages: 3W – 24W",
      "Round and square formats",
      "Recessed and surface-mounted options",
      "Warm white, natural white and daylight",
      "Brands stocked: Evoo, FHE",
    ],
    description: "SMD downlights are the standard fit for false ceilings — recessed models sit flush for a clean line, surface models mount straight onto a concrete or solid ceiling where there is no void to recess into. Available round or square in every common wattage.",
  },
  {
    id: "panel-lights",
    name: "LED Panel Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/panel-lights.jpg",
    badge: null,
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["6W", "12W", "18W", "24W", "36W", "48W", "72W"],
    shortDesc: "Slim LED panels for offices, shops and false ceilings, 6W to 72W.",
    specs: [
      "Wattages: 6W – 72W",
      "Round and square formats, plus 2x2 ft panels",
      "Even, glare-free diffused output",
      "Recessed and surface mounting frames available",
      "Brands stocked: Evoo, FHE",
    ],
    description: "Flat LED panels give an even, diffused light with far less glare than point-source fittings, which is why they dominate office and retail ceilings. The larger 2x2 ft panels replace conventional fluorescent troffers directly, with a straight swap of the ceiling tile.",
  },
  {
    id: "multi-lights",
    name: "Multi Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/multi-lights.jpg",
    badge: null,
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["12W", "18W", "24W", "36W", "48W"],
    shortDesc: "Multi-colour and multi-mode LED fittings with switchable colour tones.",
    specs: [
      "Wattages: 12W – 48W",
      "Switchable colour tone: warm / natural / daylight",
      "Multi-colour and decorative modes on selected models",
      "Recessed and surface options",
      "Brands stocked: Evoo, FHE",
    ],
    description: "Multi lights switch between warm, natural and daylight tones from the wall switch, so the same fitting can give soft light in the evening and bright working light during the day. Popular in living rooms and bedrooms where one fitting has to do both jobs.",
  },
  {
    id: "cob-lights",
    name: "COB Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/cob-lights.jpg",
    badge: null,
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["5W", "7W", "10W", "12W", "15W", "20W", "30W"],
    shortDesc: "Chip-on-board spotlights with tight, high-contrast beam control.",
    specs: [
      "Wattages: 5W – 30W",
      "Chip-on-board LED for a concentrated beam",
      "Fixed and adjustable / tiltable housings",
      "Warm white and daylight options",
      "Brands stocked: Evoo, FHE",
    ],
    description: "COB fittings put the whole LED array on a single chip, which gives a tight, well-defined beam instead of the broad wash of an SMD downlight. That makes them the right choice for accent lighting — display shelves, artwork, shop merchandise and anywhere the point is to highlight something rather than light the whole room.",
  },
  {
    id: "flood-lights",
    name: "LED Flood Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/flood-lights.jpg",
    badge: "popular",
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Wattages",
    models: ["10W", "20W", "30W", "50W", "100W", "150W", "200W", "300W"],
    shortDesc: "Weatherproof outdoor flood lights from 10W up to 300W.",
    specs: [
      "Wattages: 10W – 300W",
      "IP65 / IP66 weatherproof housings",
      "Wide beam angle for area coverage",
      "Adjustable mounting bracket",
      "Brands stocked: Evoo, FHE",
    ],
    description: "Weatherproof flood lights for boundary walls, yards, car parks, building facades and construction sites. The IP65/IP66 housings handle monsoon rain and dust without the water ingress that kills cheaper outdoor fittings inside a season. The adjustable bracket lets the beam be aimed properly after mounting.",
  },
  {
    id: "rope-lights",
    name: "LED Rope Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/rope-lights.jpg",
    badge: null,
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Options",
    models: ["Warm White", "Cool White", "RGB Multi-Colour", "Red", "Blue", "Green", "Sold per metre", "Sold per roll"],
    shortDesc: "Flexible LED rope lighting by the metre or the roll, indoor and outdoor.",
    specs: [
      "Sold per metre or by full roll",
      "Warm white, cool white, RGB and single colours",
      "Flexible PVC sleeve — weather-resistant",
      "Cuttable at marked intervals",
      "Ideal for: Cove lighting, signage, decoration and events",
    ],
    description: "Flexible rope light that bends around curves and cuts to length at marked intervals, which makes it the standard product for cove and ceiling-perimeter lighting, shopfront outlines, and wedding and event decoration. The sealed PVC sleeve holds up outdoors.",
  },
  {
    id: "neon-lights",
    name: "LED Neon Lights",
    category: "lighting",
    icon: "icon-bulb",
    image: "images/products/neon-lights.jpg",
    badge: "new",
    brands: ["Evoo", "FHE"],
    modelsLabel: "Available Options",
    models: ["Warm White", "Cool White", "RGB Multi-Colour", "Red", "Blue", "Green", "Pink", "Sold per metre", "Sold per roll"],
    shortDesc: "LED neon flex — continuous even glow with no visible dots.",
    specs: [
      "Sold per metre or by full roll",
      "Continuous diffused glow — no visible LED dots",
      "Warm white, cool white, RGB and single colours",
      "Flexible silicone body, IP65 weather-resistant",
      "Ideal for: Signage, facades, cove lighting and interiors",
    ],
    description: "LED neon flex gives the continuous even line of traditional glass neon without the fragility, the high voltage or the gas — it bends by hand, cuts to length and runs on low voltage. The dominant product now for shop signage, building facade outlines and feature interior lighting.",
  },

  // ======================================================================
  // DISTRIBUTION & BREAKERS
  // ======================================================================
  {
    id: "distribution-box-12way",
    name: "Distribution Box",
    category: "distribution",
    icon: "icon-layers",
    image: "images/products/distribution-box-12way.jpg",
    badge: null,
    modelsLabel: "Available Sizes",
    models: ["4-Way", "6-Way", "8-Way", "12-Way", "18-Way", "24-Way"],
    shortDesc: "Compact distribution box for organised, safe wiring layouts.",
    specs: [
      "Ways / circuits: 4 to 24 way",
      "Use: Indoor electrical distribution",
      "Organised layout for easier maintenance",
      "Ideal for: Home and small commercial wiring upgrades",
    ],
    description: "Keeps household or small commercial circuits organised and properly protected, making future maintenance and troubleshooting far simpler than an ad-hoc wiring setup.",
  },
  {
    id: "mcb-circuit-breaker",
    name: "MCB Circuit Breaker",
    category: "distribution",
    icon: "icon-zap",
    image: "images/products/mcb-circuit-breaker.jpg",
    badge: null,
    modelsLabel: "Available Ratings",
    models: ["6A", "10A", "16A", "20A", "25A", "32A", "40A", "63A"],
    shortDesc: "Reliable circuit protection for home and commercial panels.",
    specs: [
      "Type: Miniature Circuit Breaker (MCB)",
      "Ratings: 6A through 63A",
      "Use: Overload and short-circuit protection",
      "Fits standard distribution boards",
      "Ideal for: Homes, offices and small commercial panels",
    ],
    description: "Protects individual circuits from overloads and short circuits, automatically cutting power to prevent damage or fire risk. A standard safety component in any properly wired distribution board.",
  },
  {
    id: "auto-changeover-switch",
    name: "Automatic Changeover Switch",
    category: "distribution",
    icon: "icon-tool-alt",
    image: "images/products/auto-changeover-switch.jpg",
    badge: null,
    shortDesc: "Seamless switching between grid, solar and generator supply.",
    specs: [
      "Function: Automatic source switching",
      "Sources supported: Grid, solar/inverter and generator",
      "Reduces manual switching during outages",
      "Ideal for: Homes and businesses with multiple power sources",
    ],
    description: "Automatically switches a property between grid, solar/inverter and generator power as availability changes, removing the need to manually flip switches during an outage.",
  },

  // ======================================================================
  // SECURITY SYSTEMS
  // ======================================================================
  {
    id: "security-camera-kit-4ch",
    name: "Home Security Camera Kit (4-CH)",
    category: "security",
    icon: "icon-shield",
    image: "images/products/security-camera-kit-4ch.jpg",
    badge: null,
    shortDesc: "Complete surveillance kit with remote monitoring setup.",
    specs: [
      "Channels: 4-camera kit",
      "Monitoring: Remote viewing via phone app",
      "Includes recording unit for playback",
      "Ideal for: Homes and small business perimeter coverage",
    ],
    description: "A ready-to-install 4-camera surveillance kit covering the key entry points of a home or small business, with remote viewing so you can check in from anywhere.",
  },
  {
    id: "video-doorbell-system",
    name: "Video Doorbell System",
    category: "security",
    icon: "icon-shield",
    image: "images/products/video-doorbell-system.jpg",
    badge: null,
    shortDesc: "See and speak to visitors remotely from your phone.",
    specs: [
      "Function: Video and two-way audio doorbell",
      "Monitoring: Remote viewing via phone app",
      "Motion-triggered alerts",
      "Ideal for: Front-door visitor screening",
    ],
    description: "Lets homeowners see and speak with visitors at the door from anywhere, adding a simple extra layer of security and convenience to any entrance.",
  },
  {
    id: "cctv-nvr-8ch-kit",
    name: "CCTV NVR 8-Channel Kit",
    category: "security",
    icon: "icon-shield",
    image: "images/products/cctv-nvr-8ch-kit.jpg",
    badge: null,
    shortDesc: "Larger 8-camera surveillance system for wider coverage.",
    specs: [
      "Channels: 8-camera kit",
      "Recording: Dedicated NVR unit",
      "Monitoring: Remote viewing via phone app",
      "Ideal for: Larger homes, plazas and commercial premises",
    ],
    description: "A larger-scale surveillance setup for properties needing wider coverage than a basic kit provides — suited to bigger homes, small plazas, and commercial premises.",
  },

  // ======================================================================
  // HOME APPLIANCES
  // ======================================================================
  {
    id: "smart-wifi-switch-panel",
    name: "Smart WiFi Switch Panel",
    category: "appliances",
    icon: "icon-home",
    image: "images/products/smart-wifi-switch-panel.jpg",
    badge: null,
    shortDesc: "App and voice-controlled switch panel for everyday appliances.",
    specs: [
      "Control: WiFi app and voice assistant compatible",
      "Use: Lights, fans and everyday appliance switching",
      "Retrofits into standard switchboards",
      "Ideal for: Homes upgrading to smart control",
    ],
    description: "Brings app and voice control to everyday lights and appliances without a full rewiring job — a simple upgrade for homes wanting more convenient, modern switching.",
  },
  {
    id: "instant-water-heater",
    name: "Electric Instant Water Heater",
    category: "appliances",
    icon: "icon-home",
    image: "images/products/instant-water-heater.jpg",
    badge: null,
    shortDesc: "On-demand electric water heating for kitchens and bathrooms.",
    specs: [
      "Type: Instant (tankless) electric water heater",
      "Use: Kitchen or bathroom hot water on demand",
      "Compact wall-mounted design",
      "Ideal for: Homes wanting on-demand hot water",
    ],
    description: "Heats water on demand rather than storing it, saving space and standby energy compared to a tank-based heater. A straightforward addition for kitchens or bathrooms.",
  },
];
